workaround for exception after file upload (maybe caused by 68566b6)
exception:
undefined method `+' for nil:NilClass (NoMethodError)
/home/httpd/app/tdiary-core/tdiary/dispatcher.rb:17:in `send_headers'
/home/httpd/app/tdiary-core/update.rb:28